services:
  postgres:
    image: postgres:15
    container_name: DIVS-postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-server:
    build: ./Flask
    container_name: DIVS-flask
    restart: always
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./Flask:/app # Mount source code for live container reload
      - /app/templates # Template rendering fallback protection

  nginx:
    image: nginx:latest
    container_name: DIVS-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Flask/templates:/usr/share/nginx/html/templates:ro # Direct templates volume mount
    depends_on:
      - flask-server

volumes:
  postgres_data: